### ISSUE TITLE
Docker image for Arm64 platform is required

### ISSUE THREAD

**Issue by odidev** [brigadecore/helm-tools#1]
Hi Team,
I am trying to use the helm-tools image on arm64 platform but it seems it is not available for arm64.
I have successfully built the image using the command `docker build -t <image_name> .` on the arm64 platform with small changes in the Dockerfile.
Commit Link - c4d1e2f4345918a5306030f1daa40282df363528
Docker Hub Link - https://hub.docker.com/repository/docker/odidev/helm-tools
Do you have any plans on releasing arm64 images?
May I know how the amd64 image is getting published on Dockerhub?
If interested, I will raise a PR.

**Comment by odidev** [comment]
@krancour , can you please look into above issue?

**Comment by krancour** [comment]
Closing due to staleness. This issue will be subsumed by a larger effort to get all of Brigade working on arm64 post v2.
